robot:
  _target_: gello.robots.sim_robot.MujocoRobotServer
  xml_path: /home/rsj/gello_software/third_party/mujoco_menagerie/franka_fr3/fr3.xml
  gripper_xml_path: /home/rsj/gello_software/third_party/mujoco_menagerie/franka_emika_panda/hand.xml
  host: 127.0.0.1
  port: 6001
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/gello
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    joint_offsets:
    - 3.142
    - 3.142
    - 3.142
    - 3.142
    - 3.142
    - 3.142
    - 0.785
    joint_signs:
    - 1
    - 1
    - 1
    - -1
    - 1
    - -1
    - 1
    gripper_config:
    - 8
    - 159.621
    - 201.421
  start_joints:
  - 0.0
  - 0.0
  - 0.0
  - -1.57
  - 0.0
  - 1.57
  - 0.0
  - 0.0
hz: 100
